name: Send Google Play Apps

on:
  schedule:
    - cron: '0 * * * *'   # كل ساعة
  workflow_dispatch:      # لتشغيله يدويًا أيضاً

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python google.py
