name: Send Google Play Apps

on:
  schedule:
        - cron: '0 */4 * * *'   # كل 4 ساعات
  workflow_dispatch:      # لتشغيله يدويًا من GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python google.py

      - name: Commit last_sent_app.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_sent_app.txt
          git commit -m "Update last_sent_app.txt" || echo "No changes to commit"
          git push
